name:
    w3mimgdisplay
version:
    0.1.0.0
github:
    "prikhi/hs-w3mimgdisplay"
license:
    GPL-3
author:
    "Pavan Rikhi"
maintainer:
    "pavan.rikhi@gmail.com"
copyright:
    "GPL-3.0"
synopsis:
    Show full-resolution images in terminals with w3mimgdisplay.
category:
    Graphics, Console
extra-source-files:
    - README.md
    - CHANGELOG.md

ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

library:
    source-dirs: src

description: >
    This package provides a `W3mImgDisplay` module which allows you to render
    full-resolution images into terminals.


    It uses the
    <https://github.com/tats/w3m/blob/master/w3mimgdisplay.c w3mimgdisplay>
    program included with the <https://github.com/tats/w3m/ w3m> TUI web
    browser.


    Brick users will probably want to use the @brick-image@ package instead.


    For more information, please see the Module documentation or the repository
    on <https://github.com/prikhi/hs-w3mimgdisplay Github>.

dependencies:
    - base >= 4.7 && < 5
    - brick >=0.34
    - conduit >=1 && <2
    - data-default >=0.7 && <1
    - directory >=1.3 && <2
    - imagesize-conduit >=1.1
    - lens >=4.16 && <5
    - typed-process >=0.2 && <0.3
    - vty >=5.20
