name:                brick-image
version:             0.1.0.0
github:              "prikhi/brick-image"
license:             GPL-3
author:              "Pavan Rikhi"
maintainer:          "pavan.rikhi@gmail.com"
copyright:           "GPL-3.0"
synopsis:            Show images in your Brick UI with w3mimgdisplay.
category:            Graphics

extra-source-files:
  - README.md
  - ChangeLog.md


description: |
    This package provides an `ImageWidget` for displaying real images in a
    Brick application, using `w3mimgdisplay`.


    For more information, please see the Module documentation or the README on
    at <https://github.com/prikhi/brick-image#readme>.

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - brick >=0.34
    - conduit >=1 && <2
    - data-default >=0.7 && <1
    - directory >=1.3 && <2
    - imagesize-conduit >=1.1
    - lens >=4.16 && <5
    - typed-process >=0.2 && <0.3
    - vty >=5.20

executables:
  brick-image-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brick-image
      - brick >=0.34
      - directory >= 1.3 && <2
      - lens >=4.16 && <5
      - vector >=0.12 && <0.13
      - vty >=5.20

tests:
  brick-image-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brick-image
