name:                brick-image
version:             0.1.0.0
github:              "prikhi/brick-image"
license:             GPL-3.0
author:              "Pavan Rikhi"
maintainer:          "pavan.rikhi@gmail.com"
copyright:           "GPL-3.0"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/prikhi/brick-image#readme>

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Werror

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - brick
    - conduit
    - data-default
    - directory
    - imagesize-conduit
    - lens
    - typed-process
    - vty

executables:
  brick-image-example:
    main:                Main.hs
    source-dirs:         example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brick-image

tests:
  brick-image-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - brick-image
